### ISSUE TITLE
Carthage failed with exit code 128

### ISSUE THREAD

**Issue by 0xfeedface1993** [alexaubry/HTMLString#10]
I'm try using carthage, run **carthage update** command in bash, then error shows:

> A shell task (/usr/bin/env git clone --bare --quiet https://github.com/alexaurby/HTMLString.git /Users/virus1993/Library/Caches/org.carthage.CarthageKit/dependencies/HTMLString) failed with exit code 128:
> remote: Repository not found.
> fatal: repository 'https://github.com/alexaurby/HTMLString.git/' not found

My Carthage file:

`github "alexaurby/HTMLString" ~> 4.0`

Oooops!

It should be:

`github "alexaubry/HTMLString" ~> 4.0`

Your should correct README.md. it almost let me give up this nice framework.

Thanks to your framework, save lots of my time to Unescape some horrible text.

Have a nice day!

**Comment by alexaubry** [comment]
Ah, typos... This is fixed now. Thank you very much for reporting! 🙌
