### ISSUE TITLE
Broken Dash link

### ISSUE THREAD

**Issue by MarijnDoeve** [alexaubry/HTMLString#12]
Hi! the Dash link is pointing to `
dash-feed://https%3A%2F%2Falexaubry%2Egithub%2Eio%2Fdocsets%2FHTMLString%2Exml` (ironically this link has many html escaped characters)(`https://alexaubry.github.io/docsets/HTMLString.xml`) instead of `https://alexaubry.github.io/HTMLString/docsets/HTMLString.xml`.

And the xml file looks like:
``` XML
<entry>
    <version>4.0.0</version>
    <url>https://alexaubry.github.io/docsets/HTMLString.tgz</url>
</entry>
```
instead of `<url>https://alexaubry.github.io/HTMLString/docsets/HTMLString.tgz</url>`

This can be fixed in a pr, but maybe it's better to fix this in docs generate script thing?

**Comment by MarijnDoeve** [comment]
Found the `.generate-docs.sh`, I'm working on a pr for you :)

**Comment by alexaubry** [comment]
It's been a very long time coming but I finally fixed it! 😅 Thanks for reporting.
