### ISSUE TITLE
Xcode 10.2

### ISSUE THREAD

**Issue by priore** [alexaubry/HTMLString#15]
it's really strange but Xcode 10.2 freeze on HTMLString during a creation of the archive.

**Comment by ndreisg** [comment]
I have the same issue, though archiving continues after a very long time.

**Comment by ndreisg** [comment]
I could resolve this issue by removing `armv7` from `Valid Architectures` in the Build Settings of the HTMLString target.

If you do this you will loose support for iPhone 4S (according to this Stackoverflow answer: https://stackoverflow.com/a/52436173/7990095)

Also remove `armv7` from the project/target that is using HTMLString.

**Comment by alexaubry** [comment]
Hello, can you check by using the `swift5` branch? This should improve compilation times.

**Comment by ndreisg** [comment]
Archiving time with `swift5` branch is as expected.
Though it may be possible that this issue only occurs when installed via cocoapods (see https://stackoverflow.com/questions/55376236/xcode-10-2-hangs-during-archive-on-arbitrary-task)

**Comment by pLembo90** [comment]
> I could resolve this issue by removing `armv7` from `Valid Architectures` in the Build Settings of the HTMLString target.
> 
> If you do this you will loose support for iPhone 4S (according to this Stackoverflow answer: https://stackoverflow.com/a/52436173/7990095)
> 
> Also remove `armv7` from the project/target that is using HTMLString.


Hi, I removed arm7 like you said, but nothing changes. The archive process is very long. What do you suggest me?

**Comment by alexaubry** [comment]
@pLembo90 Did you try using the swift5 branch?

**Comment by pLembo90** [comment]
Hi Alex, thanks for your answer.
My project is written in swift 4.0. The only thing I did was update the pod to 4.0.2.

**Comment by ndreisg** [comment]
@pLembo90 
I am using the Swift 5 branch without any problems though my project is also written in Swift 4.

**Comment by acterics** [comment]
> @pLembo90 Did you try using the swift5 branch?

Swithing to swift5 branch helps, thank you!

**Comment by 2sem** [comment]
I have solved the problem by setting 'build_settings / Swift Compiler - Code Generation / Optimization Level' to 'No Optimization'
And I put automation script into Podfile 

post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
          #puts "set pod build settings. target[#{config.build_settings['MODULE_NAME']}] config[#{config.name}]"
      end
      
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if target.name == 'HTMLString' and config.name == 'Release' #settings only HTMLString/Release
            puts "set swift optimization level for release > none. target[#{target.name}]" #you can see this log when run 'pod update'
            **config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'** #this code
          end
        end
      end
  end

But, I want to make the script more short.
Please anyone let me know how can I get target.name from config

**Comment by dvkch** [comment]
Swift 5 branch helped a lot too! Thanks, hope it will soon be released as 5.0 :)

EDIT: it seams symbols like `&rsquo;` are not unescaped any longer

**Comment by raysarebest** [comment]
Compiling on `swift5` also worked for me, but it isn't the most feasible thing long-term because I need to depend on it from another CocoaPod, and the podspec stuff doesn't allow me to specify a branch to compile from. It'd be great if `swift5` could be merged into `master` and issue #21 could be addressed so I can depend on this library from my podspec

**Comment by alexaubry** [comment]
The release with the fix should be out now, as `5.0.0`. Please open another issue if you still encounter the hang.
