### ISSUE TITLE
removingHTMLEntities doesn't work if text includes non-encoded & character

### ISSUE THREAD

**Issue by ismaels** [alexaubry/HTMLString#20]
I'm using the library to remove HTML entities from Strings on my tvOS project and found out that a string like: `Mary & Joe are getting &quot;Married\"`, due to the `&` between Mary and Joe words. It returns the String as is without replacing any HTML entities.
If I remove that or even encode it as HTML entities, than calling `removingHTMLEntities` works as expected.

**Comment by alexaubry** [comment]
I fixed it on `master`. Can you try again and confirm that it works properly for you?

**Comment by alexaubry** [comment]
Closing this since there is now a unit test for the case you reported. Feel free to open a new issue if the problem persists.
