### ISSUE TITLE
Looks good, doesn't work

### ISSUE THREAD

**Issue by bernikowich-cedoni** [alexaubry/HTMLString#9]
Code won't compile on Xcode 9. Some of String init methods are optionals.

**Comment by alexaubry** [comment]
The code seems to compiles fine on Xcode 9 (both local and CI). Could you please share your compilation errors?

If you are using CocoaPods, make sure `SWIFT_VERSION` is set to Swift 4 in the Build Settings of Pods.xcodeproj, as this can be a source of errors.

**Comment by alexaubry** [comment]
I'm gonna close this issue for now. If you still have problems compiling the library, feel free to open a new one with more details :)
